### ISSUE TITLE
Difference with other libs?

### ISSUE THREAD

**Issue by rifler** [sindresorhus/type-fest#28] opened 2019-04-17 13:16 UTC
For example https://github.com/piotrwitek/utility-types
It is worth to develop one tool, I suppose

**Comment by CvX** [comment] 2019-04-17 13:17
See #3

**Comment by rifler** [comment] 2019-04-17 14:16
It doesn't answer my questions. Types are not presented in runtime, so you shouldn't worry about types that `would never use in practice`

**Comment by BendingBender** [comment] 2019-04-17 15:14
> would never use in practice

This is not about runtime. This is about maintenance burden.

**Comment by sindresorhus** [comment] 2019-04-19 08:24
Duplicate of #3

**Comment by sindresorhus** [comment] 2019-04-19 08:24
Let's continue the discussion in #3.

**Closed by sindresorhus** 2019-04-19 08:24 UTC
