### ISSUE TITLE
Proposal: `SetRequired`, `SetNonNullable`, `Schema` based on nested key path

### ISSUE THREAD

**Issue by bvandercar-vt** [sindresorhus/type-fest#688] opened 2023-09-19 20:15 UTC
Example:

```
type O = {
  record: {
    nestedrecord: {
      nestedProp?: string
    }
  }
}
```

`SetRequired<O, 'record.nestedrecord.nestedProp'>`  would have type
```
 {
  record: {
    nestedrecord: {
      nestedProp: string
    }
  }
}
```

And a similar implementation for `SetNonNullable`

`Schema` would allow changing the type of a specfic deeply-nested property, for example `Schema<O, 'record.nestedrecord.nestedProp', number>` would have type
```
{
  record: {
    nestedrecord: {
      nestedProp: number
    }
  }
}
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/688">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/688/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/688/pledge.svg">
</picture>
</a>

**Comment by fregante** [comment] 2024-11-13 02:42
Duplicate of https://github.com/sindresorhus/type-fest/issues/688

**Closed by fregante** 2024-11-13 02:42 UTC
Labels: type addition, component:paths
