### ISSUE TITLE
DeepPick and DeepPath

### ISSUE THREAD

**Issue by janek26** [sindresorhus/type-fest#735] opened 2023-10-30 09:04 UTC
Hey! Thanks for all your hard work, type-fest is very helpful in many cases!

I just wondered if you would be interested in adding DeepPick and DeepPath to it, I have a working implementation here
https://github.com/argentlabs/argent-x/blob/0cb22f7bb5b0045d8f0aebb22ee245bd59f5db8c/packages/extension/src/shared/types/deepPick.ts#L27

It works well with IDEs (autocomplete etc) and can be used just like `Pick<>` but allows for Picking nested properties by using a dot syntax (ie. `Pick<window, "location.pathname">`)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/735">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/735/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/735/pledge.svg">
</picture>
</a>

**Comment by Emiyaaaaa** [comment] 2023-10-30 09:12
Sounds useful @elmerbulthuis

**Comment by sindresorhus** [comment] 2023-10-30 10:03
👍

**Comment by sindresorhus** [comment] 2023-10-30 10:03
Kinda duplicate of https://github.com/sindresorhus/type-fest/issues/343

**Comment by janek26** [comment] 2023-11-01 09:30
Cool! If this is a go, let me know and I can create a PR @sindresorhus !

**Comment by sindresorhus** [comment] 2023-11-01 09:42
This is a go.

Just try to reuse existing internal utiltities in type-fest whenever possible.

**Comment by janek26** [comment] 2023-11-01 09:54
I'm not super familiar with all the methods type-fest provides.

Do you have anything particular in mind? Otherwise I'll try my best

**Comment by Emiyaaaaa** [comment] 2023-11-01 09:58
> Cool! If this is a go, let me know and I can create a PR @sindresorhus !

Oh sorry, my PR will be ready, Chould you review it if you want?

**Closed** 2023-11-08 20:37 UTC
Labels: help wanted, type addition
