### ISSUE TITLE
Camelcase capital letters misunderstood by DelimiterCase type

### ISSUE THREAD

**Issue by finnmerlett** [sindresorhus/type-fest#197] opened 2021-03-31 10:19 UTC
Can we get the DelimiterCase type to understand the following camelcase examples?
```ts
type Test = SnakeCase<'VATNumber'>; // expected 'VAT_number', found '_v_a_t_number'
type Test2 = SnakeCase<'returnAPICall'>; // expected 'return_API_call', found 'return_a_p_i_call'
```
The rule could be: two capital letters in a row = converted to two words with no capitals, three capital letters or more in a row = converted to two words with the first word in uppercase and the second word starting with the last of the capital letters, but in lowercase.

And also perhaps these PascalCase examples could be fixed? (this is not for my usecase though)
```ts
type Test3 = SnakeCase<'OAuth'>; // expected 'o_auth', found '_o_auth'
type Test4 = SnakeCase<'FeedAKitten'>; // expected 'feed_a_kitten', found '_feed_a_kitten'
```

I do understand this might be hideously complicated/impossible to implement - I just thought I'd ask in case!

**Comment by voxpelli** [comment] 2021-09-22 22:02
Duplicate of #223 

Sorry, I know this one was submitted first, but its the same issue as in #223 and there have been some more comments there, so I'm closing this in favor of that, but only because of that, else I would have done the reverse.

Also of interest, and very similar: https://github.com/sindresorhus/type-fest/issues/224#issuecomment-925357006

**Comment by voxpelli** [comment] 2021-09-22 22:02
Duplicate of #223

**Closed by voxpelli** 2021-09-22 22:02 UTC
Labels: bug, help wanted
