### ISSUE TITLE
Except no longer prevents the omitted keys to be keys present on the given type

### ISSUE THREAD

**Issue by nvdbleek** [sindresorhus/type-fest#360] opened 2022-02-07 15:02 UTC
The change for #263 in release [v2.3.2](https://github.com/sindresorhus/type-fest/releases/tag/v2.3.2) no longer prevents the use of the keys in the Except.

The following code no longer gives an error:

```Typescript
import { Except } from 'type-fest';

interface WithBar {
  foo: string;
  bar: number;
}

type WithoutBar = Except<WithBar, 'bar'>;

const withBar = { foo: 'Hell World', bar: 42 };
// The following assignment should result in an error, but no longer results in an error after the change of #263
const withoutBar: WithoutBar = withBar; 
```

Before 2.3.2 type-fest used `never` and you weren't allowed to assign an object that contains a key that was added to the except list. The documentation still states that Except is a stricter version of [`Omit`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-5.html#the-omit-helper-type), but I don't think it currently is.

Conceptually `type-fest` was generating the following code before `2.3.2`:

```Typescript
interface WithBarNever {
  foo: string;
  bar: never;
}

// Results in a compile error as the object should not contain a `bar` property
const withoutBarNever: WithBarNever = withBar;
```

**Comment by nvdbleek** [comment] 2022-02-07 15:09
I've created a codesandbox demonstrating the 'error' https://codesandbox.io/s/wizardly-hertz-wbv99?file=/src/index.ts

Line 12 doesn't contains a compile error (the old implementation used `never` and resulted in a compile error, see line 19 for this case)

**Comment by sindresorhus** [comment] 2022-02-07 15:49
// @szmarczak

**Comment by szmarczak** [comment] 2022-08-04 13:38
I'm not able to reproduce the issue from the first comment:

https://www.typescriptlang.org/play?ts=4.7.4&ssl=11&ssc=1&pln=11&pc=41#code/KYDwDg9gTgLgBDAnmYcCiIDGwwwDwDyARgFbCYwAqywANHANLCIDO1KcoMwAdgCYs4Aa2YQAZnGJkK7YAD44AXjgAFAJaYhhUuSo16GTABsArn2B4RicZJ0z9jZmxpy5AbgBQHtT25QxAIbYcADqajAAFgBCAVBwAN4ecHBiEBAAXHAsMFA+AOaeyUSxmTwmALZEwFCeAL5eSBxhkRAmMDFxyoY4+M3RsfQA5MVQg+5emBA82XAA7uH9nQkpaZmDABLARkah0EZ8g-QjmQAsAExwtZ6T0-DzLW0dmX2t7bFKcwsdbnBAA

**Comment by szmarczak** [comment] 2022-08-04 13:40
The code you provided in codesandbox simplifies to

```ts
const withBar = { foo: "Hell World", bar: 42 };

interface WithBarNever {
  foo: string;
  bar: never;
}

const withoutBarNever: WithBarNever = withBar;
```

which doesn't use `Except` at all.

**Comment by skarab42** [comment] 2022-09-15 09:49
I am closing this issue, it seems impossible to reproduce the error with the old or new version. Feel free to reopen this issue if you have a reproducible example.

**Closed by skarab42** 2022-09-15 09:49 UTC
Labels: bug, help wanted
