### ISSUE TITLE
Proposal: `PartialMutable` type

### ISSUE THREAD

**Issue by lesomnus** [sindresorhus/type-fest#152] opened 2020-11-25 11:32 UTC
definition
```ts
export type PartialMutable<T, K extends keyof T> = Omit<T, K> & {
	-readonly [P in K]: T[P]
};
```

usage:
```ts
type T = {
    readonly a: number
    readonly b: string
    readonly c: number[]
}

const t: PartialMutable<T, 'a' | 'b'> = { a: 42, b: 'yo', c: [1, 2, 3] };

// Valid
t.a = 3;
t.b = 'no';

// Error: ts(2540)
t.c = [4, 5, 6];

```

Please let me know if there already is.

**Comment by sindresorhus** [comment] 2020-11-25 12:05
Maybe it should be named `SetMutable` since we already have `SetOptional` and `SetRequired` types? It looks useful to me, but I'll let other people chime in too.

**Comment by sindresorhus** [comment] 2020-11-25 13:08
I just realized this is a duplicate.

**Comment by sindresorhus** [comment] 2020-11-25 13:08
Duplicate of #146

**Closed by sindresorhus** 2020-11-25 13:08 UTC
