### ISSUE TITLE
add SetExclude and SetExtract

### ISSUE THREAD

**Issue by xenoterracide** [sindresorhus/type-fest#380] opened 2022-03-21 19:28 UTC
simply similar to existing types that ensure the stringy part is really a keyof.

**Comment by sindresorhus** [comment] 2022-03-22 10:18
Duplicate of #222

**Comment by sindresorhus** [comment] 2022-03-22 10:18
See: https://github.com/sindresorhus/type-fest/pull/291

**Closed by sindresorhus** 2022-03-22 10:18 UTC
