### ISSUE TITLE
`CamelCase` does not properly camelize consecutive characters

### ISSUE THREAD

**Issue by wescopeland** [sindresorhus/type-fest#488] opened 2022-10-11 22:49 UTC
Hi!

I'm trying to use the `CamelCase` type in a project. I have the following code:

```ts
type Sample = CamelCase<"GameID">;
```

My expectation according to the docs is `Sample` would now be typed as a string value of `"gameId"`. However, it is instead typed as `"gameID"`, with __ID__ being all uppercase.

This caught me off-guard, as the example in _camel-case.d.ts_ has this code listing:

```ts
interface RawOptions {
	'dry-run': boolean;
	'full_family_name': string;
	foo: number;
	BAR: string;
	QUZ_QUX: number; // <-- here
	'OTHER-FIELD': boolean;
}

const dbResult: CamelCasedProperties<RawOptions> = {
	dryRun: true,
	fullFamilyName: 'bar.js',
	foo: 123,
	bar: 'foo',
	quzQux: 6, // <-- here
	otherField: false
};
```

For my use case, this issue impacts the `CamelCasedProperties` and `CamelCasedPropertiesDeep` types, which leverage `CamelCase`.

**Comment by sindresorhus** [comment] 2022-10-12 03:30
Duplicate of #224

**Comment by voxpelli** [comment] 2022-10-13 10:30
`CamelCase` does the following:

1. If the input is fully uppercase, it lower cases it
2. It identifies words separated by `-`, `_` and/or a space and concatenates those together with an uppercase initial character (⚠️ it currently does not lowercase the rest, this is probably to allow for conversion from `PascalCase`)
3. It uncapitalize the concatenated string

In the case of `GameID`:

1. The word is not fully uppercase, so it will not lower case it
2. There are no words that are separated by `-`, `_` and/or a space, so it will treat the input as being a single word
3. It does have an initial uppercase character which will be lower cased, hence resulting in `gameID`

I would say that this is a correct conversion.

The input is:

* not snake case
* not kebab case
* not space separated

Though the input does look to be:

* pascal case

And the correct camel case conversion of `GameID` as pascal case is `gameID`?

@wescopeland You think the above logic should be changed?

**Closed** 2022-11-04 06:33 UTC
Labels: enhancement, help wanted, component:casing
