### ISSUE TITLE
`Get<BaseType, Path>` does not work when `Path` contains `${number}`

### ISSUE THREAD

**Issue by ttlong3103** [sindresorhus/type-fest#791] opened 2024-01-05 05:04 UTC
Hi. I'm facing a problem where `Get<BaseType, Path>` does not get expected type of a property but `unknown`. Please consider the following example code:

```typescript
type Student = {
  ID: number;
  name: string;
}

interface Classroom {
  students: Student[];
}

type StudentName1 = Get<Classroom, 'students.0.name'>; // WORK. Type: string | undefined
type StudentName2 = Get<Classroom, `students.${number}.name`>; // NOT WORK. Type: unknown
```

To me, it makes sense that `StudentName2` should be `string | undefined` similar to `StudentName1`.

**Is there any way to make that possible?**

I'm using
"type-fest": "4.9.0"
"typescript": "5.3.3"

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/791">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/791/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/791/pledge.svg">
</picture>
</a>

**Comment by sindresorhus** [comment] 2024-01-06 08:39
Duplicate of #567

**Closed** 2024-04-12 20:58 UTC
Labels: component:paths
